[package]
name = "machinetree-macro"
version = "0.1.0"
authors = ["Alan Darmasaputra <kelerchian@gmail.com>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
lazy_static = "1.4.0"
syn = "1.0.86"
quote = "1.0.15"
