[package]
name = "machinetree"
version = "0.1.0"
authors = ["Alan Darmasaputra <kelerchian@gmail.com>"]
edition = "2018"
package = ["macro"]

[dependencies]
machinetree-macro = { path = "packages/machinetree-macro" }
machinetree-backend = { path = "packages/machinetree-backend" }
