[package]
name = "machinetree-core"
version = "0.1.0"
edition = "2021"

[lib]
name = "machinetree_core" 
path = "src/lib.rs"
crate-type = ["lib"]

[dependencies]
crossbeam = "0.8.1"

image = "0.24"
wgpu = { version = "0.14", features = ["spirv"] }
pollster = "0.2"
futures-intrusive = "0.4"